### ISSUE TITLE
#1258 - Jack Dorsey, Vijaya Gadde, & Tim Pool

### ISSUE THREAD

**Issue by realchrisolin** [achendrick/jrescribe-transcripts#7]
I have some GCP credits I can burn through and would like to get the transcript up for this episode sooner rather than later, but in case it's already being worked on, I thought it best to open a ticket first.

Let me know if I'm good to start working on this. Should be able to put in a PR by the end of the week. If you already have a fine-tuned process or script I can use with my own API creds to get the initial transcript, feel free to pass it over, otherwise I think I have enough of a programming background to do this myself.

**Comment by achendrick** [comment]
@realchrisolin Thanks for the offer, I'm actually processing it right now and should have it up this evening.

**Comment by achendrick** [comment]
@realchrisolin it's uploading now, but the transcript can also be viewed here https://github.com/achendrick/jrescribe-transcripts/blob/70a6479445af865b40cf41c716e837aa0e2dcdad/p1258.md
